[execution]
url = "https://www.grabcraft.com/minecraft/abstract-house-4/other-193#blueprints"
skip = 0
material = "potted"
stair_direction = "auto"

[coordinates]
offset_x = -115
offset_y = 64
offset_z = 180

[screen_regions.panel_region]
x = 75
y = 647
width = 75
height = 30

[screen_regions.health_region]
x = 450
y = 1357
width = 200
height = 20

[screen_regions.command_region]
x = 1255
y = 1395
width = 15
height = 40
