[execution]
url = "https://www.grabcraft.com/minecraft/the-burning-bear-inn/medieval-houses#blueprints"
skip = 0
material = "_sign"

[coordinates]
offset_x = -70
offset_y = 68
offset_z = 89

[screen_regions.panel_region]
x = 75
y = 647
width = 75
height = 30

[screen_regions.health_region]
x = 450
y = 1357
width = 200
height = 20

[screen_regions.command_region]
x = 1255
y = 1395
width = 15
height = 40
